# Generated by Django 2.1.3 on 2018-12-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
    ]
