# Generated by Django 2.1.3 on 2018-12-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0002_remove_movie_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, upload_to='poster'),
        ),
    ]
